// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7R7PYuy5HHG5XIrgdMFXMTweb0gNFoUs',
    appId: '1:457279058464:web:2776ebb95e328e0da50245',
    messagingSenderId: '457279058464',
    projectId: 'evrvvinrub',
    authDomain: 'evrvvinrub.firebaseapp.com',
    storageBucket: 'evrvvinrub.appspot.com',
    measurementId: 'G-11QFRG275J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVwvBcfLotM0JnCR0BAOjfhPXxg5NfvFY',
    appId: '1:457279058464:android:362fd5ccfa8331bea50245',
    messagingSenderId: '457279058464',
    projectId: 'evrvvinrub',
    storageBucket: 'evrvvinrub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7BQ_dXFIC6VIheZarF3BaQc7907ND1tU',
    appId: '1:457279058464:ios:88ebd878afab6fe2a50245',
    messagingSenderId: '457279058464',
    projectId: 'evrvvinrub',
    storageBucket: 'evrvvinrub.appspot.com',
    iosClientId: '457279058464-m5naeefvothvn3hhq3tl93a1vllhbka7.apps.googleusercontent.com',
    iosBundleId: 'com.evcsrc.evscrs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7BQ_dXFIC6VIheZarF3BaQc7907ND1tU',
    appId: '1:457279058464:ios:88ebd878afab6fe2a50245',
    messagingSenderId: '457279058464',
    projectId: 'evrvvinrub',
    storageBucket: 'evrvvinrub.appspot.com',
    iosClientId: '457279058464-m5naeefvothvn3hhq3tl93a1vllhbka7.apps.googleusercontent.com',
    iosBundleId: 'com.evcsrc.evscrs',
  );
}
